FROM caddy:2-alpine
WORKDIR /tailwind

RUN apk add --no-cache npm watchexec
COPY package.json ./
RUN npm install

COPY docker/Caddyfile.dev /etc/caddy/Caddyfile
COPY docker/startup.caddy.dev.sh /startup.sh
RUN chmod +x /startup.sh
ENTRYPOINT ["/startup.sh"]
