FROM node:22-alpine AS builder
WORKDIR /build

COPY . .
RUN npm install
RUN npm run build

FROM caddy:2-alpine
WORKDIR /etc/caddy

COPY docker/Caddyfile.prod ./Caddyfile
COPY public /var/www/public
COPY src /var/www/public
COPY --from=builder /var/www/public/style.css /var/www/public
